/** 首页批注配置 */
export const homeAnnotations = {
  notifyBell: {
    title: '消息通知铃铛',
    requirementLogic: '登录检测员可见；未读数来自通知中心未读条数统计。',
    displayRule: '未读 > 0 时右上角显示红色角标数字；无未读仅展示铃铛图标。',
    interactionLogic: '点击打开消息通知 overlay（列表 + 详情）；退回复测类支持「去处理」深链。',
    elementAnalysis: '① 铃铛 SVG 图标（24px）；② 未读角标：minWidth 16、红底白字、未读=0 时隐藏；③ 按钮区 40×40 透明底。状态：有未读/无未读两种。',
  },
  companyHeader: {
    title: '公司标题栏',
    requirementLogic: '展示当前登录用户所属公司全称，建立页面品牌上下文。',
    displayRule: 'SectionTitle 左对齐；右侧与通知铃铛同一行两端对齐。',
    interactionLogic: '纯展示，不可点击。',
    elementAnalysis: '① 公司名称文本（杭州数蚕智能科技有限公司）；② 与铃铛按钮 flex 两端对齐。无多状态。',
  },
  brandBanner: {
    title: '品牌宣传条',
    requirementLogic: '首页顶部品牌露出，传达产品定位。',
    displayRule: '深蓝底圆角卡片；含系统名、主标语、副标语；右上装饰圆。',
    interactionLogic: '纯展示。',
    elementAnalysis: '① 小字「实验室数智化系统」；② 主标题「试验数据·实时自动采集」；③ 副文案「采集即上传…」；④ 背景装饰圆。无交互态。',
  },
  workOverview: {
    title: '今日工作概览',
    requirementLogic: '仅展示需优先处理的异常维度：逾期、3 日内到期、退回复测；不含与快捷入口重复的「检测中」。',
    displayRule: '数值取自 inspectorWorkMetrics；三卡横向等分排列。',
    interactionLogic: '分别进入 focus overlay：overdue / dueSoon / returned 聚焦页 L2 任务列表。',
    elementAnalysis: '① 区块标题「今日工作概览」；② 说明文案一行；③ 下方三 StatCard 容器。状态：仅展示态。',
  },
  overdueCard: {
    title: '逾期任务卡',
    requirementLogic: '统计检测时效已过且任务未完成的委托任务数。',
    displayRule: '逾期色调 StatCard；数值为 0 时仍展示。',
    interactionLogic: '点击进入 overdue 聚焦页 L2。',
    elementAnalysis: '① 标签「逾期任务」；② 数值（红色系）；③ 可点击卡片 hover 阴影。状态：count=0 仍显示 0。',
  },
  dueSoonCard: {
    title: '3日内到期卡',
    requirementLogic: '统计检测时效在未来 3 日内且未完成的任务数。',
    displayRule: '临期色调 StatCard；与逾期、退回并列。',
    interactionLogic: '点击进入 dueSoon 聚焦页 L2。',
    elementAnalysis: '① 标签「3日内到期」；② 数值（黄色系）；③ 整卡可点。状态：0 值仍展示。',
  },
  returnedCard: {
    title: '退回复测卡',
    requirementLogic: '统计含退回试验项的委托任务数。',
    displayRule: '品牌蓝色调 StatCard。',
    interactionLogic: '点击进入 returned 聚焦页 L2。',
    elementAnalysis: '① 标签「退回复测」；② 数值（蓝色系）；③ 可点击。状态：无退回时显示 0。',
  },
  quickPending: {
    title: '快捷入口·待检任务',
    requirementLogic: '统计当前检测员名下 status 为 pending 的委托任务数。',
    displayRule: '数字 + 待检色调；任务数为 0 仍展示 0。',
    interactionLogic: '点击打开 pending 聚焦页（L2 任务列表，支持扫码进 L3）。',
    elementAnalysis: '① 圆形图标底（黄）；② inbox 图标；③ 数字；④ 标签「待检任务」。状态：固定四行纵向排列。',
  },
  quickTesting: {
    title: '快捷入口·检测中任务',
    requirementLogic: '统计 status 为 testing 的委托任务数。',
    displayRule: '检测中蓝色调 Quick 卡。',
    interactionLogic: '点击打开 testing 聚焦页 L2。',
    elementAnalysis: '① loader 图标圆底；② 数字；③ 标签「检测中任务」。与待检/已检结构一致，色调不同。',
  },
  quickDone: {
    title: '快捷入口·已检任务',
    requirementLogic: '统计 status=done 且有 doneAt 的任务数。',
    displayRule: '已完成绿色调 Quick 卡。',
    interactionLogic: '点击打开 done 已完成任务 overlay。',
    elementAnalysis: '① check 图标圆底；② 数字；③ 标签「已检任务」。',
  },
  inspectorStats: {
    title: '个人检测统计',
    requirementLogic: '展示当前检测员本人样品量与试验量趋势，支持时间区间切换。',
    displayRule: '日期区间 + 本年/本季/本月 SegmentedSwitch；两张折线图 Card。',
    interactionLogic: '切换区间刷新图表数据；图表只读不可钻取。',
    elementAnalysis: '① 起止日期只读框+日历图标；② 三段切换器；③「样品检测量」折线图（蓝线+圆点+Y 轴刻度）；④「试验检测量」折线图（橙线）。状态：year/quarter/month 三套 mock 数据。',
  },
};
