/** 检测模块批注配置（L1/L2/L3 共用） */
export const inspectAnnotations = {
  modeSwitch: {
    title: '按设备 / 按任务切换',
    requirementLogic: '两种钻取路径互斥：按设备从设备出发；按任务从委托任务出发。',
    displayRule: '分段切换控件；切换时重置 L2/L3 钻取状态与搜索关键词。',
    interactionLogic: '切换后停留在 L1 列表；按任务模式不展示工位栏。',
    elementAnalysis: '① SegmentedSwitch 两段：「按设备」「按任务」；② 选中段高亮底+字重。状态：device | task。',
  },
  stationPicker: {
    title: '工位选择（按设备）',
    requirementLogic: '按设备模式下筛选当前工位关联设备；未选工位展示全部设备。',
    displayRule: '定位图标+工位名（超长省略）+「切换」+ 清除按钮（已选工位时）。',
    interactionLogic: '切换打开工位 BottomSheet；清除清空 stationId。',
    elementAnalysis: '① 定位 SVG；② 工位名文本 maxWidth 108；③ 切换按钮；④ 清除×（仅 station 有值）。状态：未选/已选工位。',
  },
  searchBar: {
    title: '搜索与扫码',
    requirementLogic: 'L1 按模式切换 placeholder；L3 搜试样编号与试验项。',
    displayRule: 'SearchBar 带扫码图标（L1/L2 有，部分 L3 无）。',
    interactionLogic: '输入实时过滤；扫码打开 ScanSampleOverlay 模拟进 L3。',
    elementAnalysis: '① 输入框；② 搜索图标；③ 扫码按钮（可选）。状态：有/无关键词；扫码 overlay 开/关。',
  },
  methodFilter: {
    title: '采集方式筛选',
    requirementLogic: '按设备 L1 可按 auto/ble/ocr 等采集方式过滤设备列表。',
    displayRule: 'MethodFilterChips 横滑芯片，展示各方式设备计数。',
    interactionLogic: '单选切换过滤；再点取消选中。',
    elementAnalysis: '① 各采集方式 Chip（CollectBadge 色）；② 括号内计数。状态：未选/选中某方式。',
  },
  deviceCard: {
    title: '设备卡片（L1）',
    requirementLogic: '展示工位内可检设备，点击进入该设备 L2 任务列表。',
    displayRule: 'DeviceCard：名称、编号、型号、区域、采集方式、关联试验项数。',
    interactionLogic: '点击进入 L2 选择委托任务。',
    elementAnalysis: '① 设备名加粗；② 编号·型号副文；③ 区域标签；④ CollectBadge；⑤ 试验项数量。状态：列表/空态「无匹配设备」。',
  },
  offDevicePanel: {
    title: '非工位设备折叠区',
    requirementLogic: '未绑定工位的便携设备单独折叠展示，避免与工位设备混淆。',
    displayRule: '虚线边框 BLE 色；折叠标题含台数；展开后 DeviceCard 列表。',
    interactionLogic: '点击标题展开/收起；展开后卡片同 L1 设备。',
    elementAnalysis: '① 折叠标题行+箭头（旋转 180°）；② 展开列表。状态：offOpen true/false。',
  },
  taskSort: {
    title: '任务排序',
    requirementLogic: '委托任务列表支持按时效、下发时间等排序。',
    displayRule: 'TaskListSort 下拉/芯片组展示当前排序字段与方向。',
    interactionLogic: '切换排序后列表即时重排。',
    elementAnalysis: '① 排序标签；② 当前排序项高亮。状态：detectDeadline:asc 等组合。',
  },
  taskList: {
    title: '委托任务列表（L1 按任务）',
    requirementLogic: '按任务模式下展示全部可检任务；支持排序与关键词过滤。',
    displayRule: 'TaskCard 展示编号、样品名、委托单位、时效与状态标签。',
    interactionLogic: '点击任务卡进入 L3（样品左栏 + 试验项右栏）；搜索框右侧可扫码直达 L3。',
    elementAnalysis: '① TaskCard 多行：编号、样品名、委托单位、下发时间、检测时效、StatusTag。状态：pending/testing/overdue/done 等。',
  },
  deviceSummary: {
    title: '设备摘要（L2 按设备）',
    requirementLogic: '进入 L2 后展示当前选中设备信息，确认检测对象。',
    displayRule: 'Card 含设备名、编号型号、CollectBadge。',
    interactionLogic: '只读；返回回 L1。',
    elementAnalysis: '① 设备名 lg 加粗；② 编号·型号；③ 采集方式 Badge。无多状态。',
  },
  deviceTaskList: {
    title: '设备相关任务（L2）',
    requirementLogic: '仅展示该设备可参与的委托任务。',
    displayRule: 'TaskCard 列表 + 任务数标题。',
    interactionLogic: '点击进 L3，样品/试验项按设备过滤。',
    elementAnalysis: '同 taskList TaskCard 元素；空态「暂无涉及该设备的委托任务」。',
  },
  taskSummary: {
    title: '任务摘要（L3）',
    requirementLogic: 'L3 顶栏展示当前委托任务关键信息。',
    displayRule: 'Card：任务编号、StatusTag、委托单位、样品数、下发时间、检测时效（逾期红色）。',
    interactionLogic: '只读。',
    elementAnalysis: '① 编号+StatusTag 行；② 网格副信息。状态：task.status 影响标签色与时效色。',
  },
  sampleSidebar: {
    title: '样品左栏（L3）',
    requirementLogic: '多样品任务时切换当前样品，驱动右侧试验项列表。',
    displayRule: '160px 宽按钮列表：StatusTag、序号、编号、样品名（两行截断）；选中左蓝条+浅底；扫码进入高亮框。',
    interactionLogic: '点击切换样品；点击样品名可弹出全名 tooltip。',
    elementAnalysis: '① StatusTag；② 序号；③ 样品编号；④ 样品名（2 行 clamp）。状态：选中 on / 扫码高亮 isFrom / 默认。',
  },
  testItemCard: {
    title: '试验项卡片（L3）',
    requirementLogic: '仅展示当前样品下试验项；按设备模式过滤为该设备可做项。',
    displayRule: 'TestItemCard：试验名、设备、采集方式、状态、逾期标签。',
    interactionLogic: '点击进入 L4 采集页（Collect / CollectLite / CollectStructured）。',
    elementAnalysis: '① 试验名；② 设备文案；③ CollectBadge/多方式；④ StatusTag；⑤ overdueTag。状态：pending/testing/done + 逾期标记。',
  },
};
